"""Add pricing_strategy to ServiceDefinition

Revision ID: 04ccba92898f
Revises: 4cc9b8007fc1
Create Date: 2025-12-30 08:41:07.635941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04ccba92898f'
down_revision: Union[str, Sequence[str], None] = '4cc9b8007fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('pricing_strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'pricing_strategy')
    # ### end Alembic commands ###
