"""add_type_to_vendor

Revision ID: 1aa0c0b07e8f
Revises: 7a409df756b5
Create Date: 2026-01-01 03:08:11.117357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa0c0b07e8f'
down_revision: Union[str, Sequence[str], None] = '7a409df756b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('vendors', sa.Column('type', sa.String(), nullable=True))
    
    # 2. Update existing rows
    op.execute("UPDATE vendors SET type = 'EXTERNAL'")
    
    # 3. Alter to not null
    op.alter_column('vendors', 'type', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'type')
    # ### end Alembic commands ###
