"""add_audit_columns_to_service_definition

Revision ID: 1c464deaf082
Revises: 3c8fd4753001
Create Date: 2026-01-08 20:46:40.278083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c464deaf082'
down_revision: Union[str, Sequence[str], None] = '3c8fd4753001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('service_definition', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_definition', 'user', ['updated_by_id'], ['id'])
    op.create_foreign_key(None, 'service_definition', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_definition', type_='foreignkey')
    op.drop_constraint(None, 'service_definition', type_='foreignkey')
    op.drop_column('service_definition', 'updated_by_id')
    op.drop_column('service_definition', 'created_by_id')
    # ### end Alembic commands ###
