"""add supportticket participants table

Revision ID: 27142167bced
Revises: b09f8992ca32
Create Date: 2026-01-04 22:49:20.228849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27142167bced'
down_revision: Union[str, Sequence[str], None] = 'b09f8992ca32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_participants',
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    op.drop_index(op.f('ix_support_ticket_status'), table_name='support_ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_support_ticket_status'), 'support_ticket', ['status'], unique=False)
    op.drop_table('ticket_participants')
    # ### end Alembic commands ###
