"""add support ban and message attachments

Revision ID: 2e1dd3d2121a
Revises: dce2dc4d6725
Create Date: 2026-01-09 12:28:46.760821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e1dd3d2121a'
down_revision: Union[str, Sequence[str], None] = 'dce2dc4d6725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_message', sa.Column('attachments', sa.Text(), nullable=True))
    op.alter_column('transaction', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('transaction', 'claimed_currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('support_banned_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('is_support_banned_permanently', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('support_violation_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'support_violation_count')
    op.drop_column('user', 'is_support_banned_permanently')
    op.drop_column('user', 'support_banned_until')
    op.alter_column('transaction', 'claimed_currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transaction', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('ticket_message', 'attachments')
    # ### end Alembic commands ###
