"""add account activation fields

Revision ID: 2e7639f2b837
Revises: a160fc259479
Create Date: 2026-01-13 05:11:15.895698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7639f2b837'
down_revision: Union[str, Sequence[str], None] = 'a160fc259479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('activation_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('activation_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_activation_token'), 'user', ['activation_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_activation_token'), table_name='user')
    op.drop_column('user', 'activation_token_expires')
    op.drop_column('user', 'activation_token')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
