"""add_audit_columns_to_core_models

Revision ID: 3c8fd4753001
Revises: cc385af9a5a9
Create Date: 2026-01-08 20:40:52.396511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c8fd4753001'
down_revision: Union[str, Sequence[str], None] = 'cc385af9a5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_request', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('service_request', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_service_request_created_at'), table_name='service_request')
    op.drop_index(op.f('ix_service_request_service_def_id'), table_name='service_request')
    op.create_foreign_key(None, 'service_request', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'service_request', 'user', ['updated_by_id'], ['id'])
    op.add_column('support_ticket', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'support_ticket', 'user', ['updated_by_id'], ['id'])
    op.add_column('transaction', sa.Column('updated_by_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.create_foreign_key(None, 'transaction', 'user', ['updated_by_id'], ['id'])
    op.drop_index(op.f('ix_vendor_transactions_created_at'), table_name='vendor_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vendor_transactions_created_at'), 'vendor_transactions', ['created_at'], unique=False)
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.drop_column('transaction', 'updated_by_id')
    op.drop_constraint(None, 'support_ticket', type_='foreignkey')
    op.drop_column('support_ticket', 'updated_by_id')
    op.drop_constraint(None, 'service_request', type_='foreignkey')
    op.drop_constraint(None, 'service_request', type_='foreignkey')
    op.create_index(op.f('ix_service_request_service_def_id'), 'service_request', ['service_def_id'], unique=False)
    op.create_index(op.f('ix_service_request_created_at'), 'service_request', ['created_at'], unique=False)
    op.drop_column('service_request', 'updated_by_id')
    op.drop_column('service_request', 'created_by_id')
    # ### end Alembic commands ###
