"""add is_public to servicedefinition

Revision ID: 45b123fa741b
Revises: 770070aa99ab
Create Date: 2026-01-03 23:12:01.858140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b123fa741b'
down_revision: Union[str, Sequence[str], None] = '770070aa99ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'is_public')
    # ### end Alembic commands ###
