"""Add default_vendor_id to ServiceVariant

Revision ID: 5b32a0f777c3
Revises: c0c1c9f48ba4
Create Date: 2025-12-31 02:42:02.699715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b32a0f777c3'
down_revision: Union[str, Sequence[str], None] = 'c0c1c9f48ba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_variants', sa.Column('default_vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_variants', 'vendors', ['default_vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_variants', type_='foreignkey')
    op.drop_column('service_variants', 'default_vendor_id')
    # ### end Alembic commands ###
