"""add staff category and office to user

Revision ID: 5be4c7aa9e1c
Revises: 45b123fa741b
Create Date: 2026-01-04 21:33:58.187794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5be4c7aa9e1c'
down_revision: Union[str, Sequence[str], None] = '45b123fa741b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('staff_category', sa.String(), nullable=True))
    op.add_column('user', sa.Column('work_office', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'work_office')
    op.drop_column('user', 'staff_category')
    # ### end Alembic commands ###
