"""add password reset fields to user

Revision ID: 61342f5e5ef4
Revises: 2e1dd3d2121a
Create Date: 2026-01-12 23:28:59.113893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61342f5e5ef4'
down_revision: Union[str, Sequence[str], None] = '2e1dd3d2121a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'1'::double precision"))
    op.alter_column('transaction', 'claimed_currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'SAR'::character varying"))
    op.add_column('user', sa.Column('password_reset_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_password_reset_token'), 'user', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_password_reset_token'), table_name='user')
    op.drop_column('user', 'password_reset_expires')
    op.drop_column('user', 'password_reset_token')
    op.alter_column('transaction', 'claimed_currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'SAR'::character varying"))
    op.alter_column('transaction', 'exchange_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'1'::double precision"))
    # ### end Alembic commands ###
