"""Add transaction_id to VendorTransaction

Revision ID: 67a4f23070e9
Revises: 5b32a0f777c3
Create Date: 2025-12-31 19:02:46.835092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67a4f23070e9'
down_revision: Union[str, Sequence[str], None] = '5b32a0f777c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_definition', 'form_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('service_definition', 'pricing_strategy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('service_request', 'form_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.add_column('vendor_transactions', sa.Column('transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_vendor_transactions_transaction_id'), 'vendor_transactions', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_transactions_transaction_id'), table_name='vendor_transactions')
    op.drop_column('vendor_transactions', 'transaction_id')
    op.alter_column('service_request', 'form_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('service_definition', 'pricing_strategy',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('service_definition', 'form_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
