"""Add account lockout fields

Revision ID: 711fec08b04e
Revises: 61342f5e5ef4
Create Date: 2026-01-13 02:37:46.524924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '711fec08b04e'
down_revision: Union[str, Sequence[str], None] = '61342f5e5ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('last_failed_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_locked_until')
    op.drop_column('user', 'last_failed_login')
    op.drop_column('user', 'failed_login_attempts')
    # ### end Alembic commands ###
