"""add nid_number to user

Revision ID: 770070aa99ab
Revises: de8dd966c735
Create Date: 2026-01-03 21:10:24.122240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770070aa99ab'
down_revision: Union[str, Sequence[str], None] = 'de8dd966c735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nid_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nid_number')
    # ### end Alembic commands ###
