"""Add financial_schema and breakdown

Revision ID: 7a409df756b5
Revises: 67a4f23070e9
Create Date: 2025-12-31 19:52:42.161709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a409df756b5'
down_revision: Union[str, Sequence[str], None] = '67a4f23070e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('financial_schema', sa.JSON(), nullable=True))
    op.add_column('service_request', sa.Column('financial_breakdown', sa.JSON(), nullable=True))
    op.alter_column('vendor_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('service_request', 'financial_breakdown')
    op.drop_column('service_definition', 'financial_schema')
    # ### end Alembic commands ###
