"""add bengali fields to notification

Revision ID: 947e5f4c4e6f
Revises: c6d86bf02c7f
Create Date: 2026-01-13 02:03:24.000060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947e5f4c4e6f'
down_revision: Union[str, Sequence[str], None] = 'c6d86bf02c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('title_bn', sa.String(), nullable=True))
    op.add_column('notification', sa.Column('message_bn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'message_bn')
    op.drop_column('notification', 'title_bn')
    # ### end Alembic commands ###
