"""add_user_services_scope

Revision ID: 9fa1baf228d8
Revises: 1aa0c0b07e8f
Create Date: 2026-01-02 02:37:28.781445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa1baf228d8'
down_revision: Union[str, Sequence[str], None] = '1aa0c0b07e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_services',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('service_def_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_def_id'], ['service_definition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'service_def_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_services')
    # ### end Alembic commands ###
