"""add_coupon_config_to_service_definition

Revision ID: af11dbcf4152
Revises: 03c8644feda3
Create Date: 2026-01-15 06:50:16.899579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af11dbcf4152'
down_revision: Union[str, Sequence[str], None] = '03c8644feda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('coupon_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'coupon_config')
    # ### end Alembic commands ###
