"""add is_available to service

Revision ID: b09f8992ca32
Revises: 5be4c7aa9e1c
Create Date: 2026-01-04 22:08:59.612613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09f8992ca32'
down_revision: Union[str, Sequence[str], None] = '5be4c7aa9e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'is_available')
    # ### end Alembic commands ###
