"""add_category_and_created_by_to_support_ticket

Revision ID: b4981e7177af
Revises: 1aa0c0b07e8f
Create Date: 2026-01-02 02:46:27.229723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4981e7177af'
down_revision: Union[str, Sequence[str], None] = '1aa0c0b07e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_ticket', sa.Column('category', sa.String(), nullable=True))
    op.add_column('support_ticket', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'support_ticket', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_ticket', type_='foreignkey')
    op.drop_column('support_ticket', 'created_by_id')
    op.drop_column('support_ticket', 'category')
    # ### end Alembic commands ###
