"""add_financial_tracking_to_vendor_transaction

Revision ID: b64a88f25874
Revises: 44aad9292ec9
Create Date: 2026-01-14 14:05:01.259000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b64a88f25874'
down_revision: Union[str, Sequence[str], None] = '44aad9292ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_transactions', sa.Column('reference_id', sa.String(), nullable=True))
    op.add_column('vendor_transactions', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('vendor_transactions', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('vendor_transactions', sa.Column('proof_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_vendor_transactions_reference_id'), 'vendor_transactions', ['reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_transactions_reference_id'), table_name='vendor_transactions')
    op.drop_column('vendor_transactions', 'proof_url')
    op.drop_column('vendor_transactions', 'exchange_rate')
    op.drop_column('vendor_transactions', 'currency')
    op.drop_column('vendor_transactions', 'reference_id')
    # ### end Alembic commands ###
