"""Add ServiceVariant model and update ServiceRequest

Revision ID: c0c1c9f48ba4
Revises: fd3bc6633cb8
Create Date: 2025-12-31 00:54:42.692359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0c1c9f48ba4'
down_revision: Union[str, Sequence[str], None] = 'fd3bc6633cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_def_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_bn', sa.String(), nullable=True),
    sa.Column('price_model', sa.String(), nullable=True),
    sa.Column('default_price', sa.Float(), nullable=True),
    sa.Column('default_cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_def_id'], ['service_definition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_variants_id'), 'service_variants', ['id'], unique=False)
    op.add_column('service_request', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_request', 'service_variants', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_request', type_='foreignkey')
    op.drop_column('service_request', 'variant_id')
    op.drop_index(op.f('ix_service_variants_id'), table_name='service_variants')
    op.drop_table('service_variants')
    # ### end Alembic commands ###
