"""add bengali translations to service definition

Revision ID: c6d86bf02c7f
Revises: 61342f5e5ef4
Create Date: 2026-01-13 01:13:46.301239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d86bf02c7f'
down_revision: Union[str, Sequence[str], None] = '61342f5e5ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('name_bn', sa.String(), nullable=True))
    op.add_column('service_definition', sa.Column('description_bn', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'description_bn')
    op.drop_column('service_definition', 'name_bn')
    # ### end Alembic commands ###
