"""add_claimed_amount_to_vendor_transaction

Revision ID: c758bc9f4e68
Revises: b64a88f25874
Create Date: 2026-01-14 14:10:11.703843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c758bc9f4e68'
down_revision: Union[str, Sequence[str], None] = 'b64a88f25874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_transactions', sa.Column('claimed_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_transactions', 'claimed_amount')
    # ### end Alembic commands ###
