"""add_coupon_code_to_transaction

Revision ID: e53a691e1789
Revises: af11dbcf4152
Create Date: 2026-01-15 07:08:28.649460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53a691e1789'
down_revision: Union[str, Sequence[str], None] = 'af11dbcf4152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('coupon_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'coupon_code')
    # ### end Alembic commands ###
