"""add image_url to servicedefinition

Revision ID: e8b4f76618de
Revises: 67b7a41f94ef
Create Date: 2026-01-03 08:31:24.529916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b4f76618de'
down_revision: Union[str, Sequence[str], None] = '67b7a41f94ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_definition', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_definition', 'image_url')
    # ### end Alembic commands ###
