"""Add Vendor system and update ServiceRequest commerce fields

Revision ID: fd3bc6633cb8
Revises: 04ccba92898f
Create Date: 2025-12-31 00:42:18.680307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd3bc6633cb8'
down_revision: Union[str, Sequence[str], None] = '04ccba92898f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=False)
    op.create_table('vendor_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_transactions_id'), 'vendor_transactions', ['id'], unique=False)
    op.add_column('service_request', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.add_column('service_request', sa.Column('cost_price', sa.Float(), nullable=True))
    op.add_column('service_request', sa.Column('selling_price', sa.Float(), nullable=True))
    op.add_column('service_request', sa.Column('profit', sa.Float(), nullable=True))
    op.add_column('service_request', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_request', 'vendors', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_request', type_='foreignkey')
    op.drop_column('service_request', 'quantity')
    op.drop_column('service_request', 'profit')
    op.drop_column('service_request', 'selling_price')
    op.drop_column('service_request', 'cost_price')
    op.drop_column('service_request', 'vendor_id')
    op.drop_index(op.f('ix_vendor_transactions_id'), table_name='vendor_transactions')
    op.drop_table('vendor_transactions')
    op.drop_index(op.f('ix_vendors_name'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    # ### end Alembic commands ###
