"""add_profile_fields_to_user

Revision ID: fef79fa7235b
Revises: 67b7a41f94ef
Create Date: 2026-01-03 03:07:41.415016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fef79fa7235b'
down_revision: Union[str, Sequence[str], None] = '67b7a41f94ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('user', sa.Column('nationality', sa.String(), nullable=True))
    op.add_column('user', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('passport_expiry', sa.String(), nullable=True))
    op.add_column('user', sa.Column('visa_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('visa_expiry', sa.String(), nullable=True))
    op.add_column('user', sa.Column('iqama_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('iqama_expiry', sa.String(), nullable=True))
    op.add_column('user', sa.Column('address_line1', sa.String(), nullable=True))
    op.add_column('user', sa.Column('address_line2', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(), nullable=True))
    op.add_column('user', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'country')
    op.drop_column('user', 'zip_code')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address_line2')
    op.drop_column('user', 'address_line1')
    op.drop_column('user', 'iqama_expiry')
    op.drop_column('user', 'iqama_number')
    op.drop_column('user', 'visa_expiry')
    op.drop_column('user', 'visa_number')
    op.drop_column('user', 'passport_expiry')
    op.drop_column('user', 'passport_number')
    op.drop_column('user', 'nationality')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
